#!/bin/bash

current_session_by_name="$(tmux display-message -p \#S):$(tmux display-message -p \#W)"
current_session_by_id="$(tmux display-message -p \#S):$(tmux display-message -p \#I)"

if [[ "$current_session_by_name" == "utils:music" ]]; then
    # switch back to _last_before_music
    last_before_music=$(tmux display-message -p "#{@_last_before_music}")

    if [[ ! -z $last_before_music ]] && tmux has-session -t$last_before_music > /dev/null 2>&1; then
        tmux switch-client -t$last_before_music
    fi
else
    # not in utils:music, switch to the music
    tmux set -g @_last_before_music "$current_session_by_id"
    ~/.local/bin/tss music
fi
