#!/bin/bash

work_dirs="$HOME/projects:$HOME/projects/scripts"

if [[ $1 == "gen" ]]; then
    if ! tmux has-session -t general 2>/dev/null; then
        tmux new-session -ds general
        tmux new-window -t general
    fi
    if [[ -z $TMUX ]]; then
        tmux attach
    fi
    tmux switch-client -t general:0
    exit 0
fi

session=$(tr ":" "\n" <<<"$work_dirs" \
    | xargs -I {} find {} -maxdepth 1 \
    | sed "1d" \
    | fzf)

if [[ -z $session ]]; then
    last_session=$(tmux display-message -p "#{@_last_session}")
    if [[ ! -z $last_session ]]; then
        tmux switch-client -t$last_session
    fi
    exit 1
fi

is_tmux_running=$(pgrep tmux)

# if tmux is running check for the session
# if session exist switch to the session
# else start the session and switch to it

session_name=$(basename "$session" | tr " " "_")

create_session () {
    if [ -f $HOME/.config/tss/startup/$session_name ]; then
        # running the start up script for this session, if it exists
        . $HOME/.config/tss/startup/$session_name
    else
        # else 0th window will be the terminal
        # and 1st wiil be the nvim
        tmux send-keys -t$session_name:0 "cd $session" Enter
        tmux new-window -t$session_name
        tmux send-keys -t$session_name:1 "cd $session" Enter
        tmux send-keys -t$session_name:1 "nvim" Enter
    fi
}

if [[ ! -z $TMUX || ! -z $is_tmux_running ]]; then
    # tmux is running
    echo tmux is running
    if ! tmux has-session -t$session_name 2>/dev/null; then
        tmux new-session -ds $session_name
        create_session
    fi

    if [[ -z $TMUX ]]; then
        tmux attach
    fi

else
    # tmux is not running
    echo tmux is not running
    tmux new-session -ds $session_name
    create_session
    tmux attach
fi

tmux switch-client -t$session_name
tmux previous-layout

exit 0
