#!/bin/bash

unset dirs_for_syllabus
unset dirs_for_notes
unset gen_type
unset modified_cover_title
unset modified_time_norg

check_metadata () {

	# First Arg --> path to the norg file

	local meta

	if [[ -f  "$1" ]]; then
		meta=$(sed -n "0,/@end/p" "$1")
		if grep "@document.meta" <<<"$meta" > /dev/null 2>&1 ; then
			return 0
		fi
		printf "Couldn't extract metadata from the norg file: \""$1"\"\nExiting...\n"
	else
		printf "Couldn't find norg file: \"$1/\"\nExiting...\n"
	fi
	exit 1
}

write_new_modt () {

	local path
	local time
	local line="${!1}"

	[[ -z $line ]] && return 1

	path=${line%@*}
	time=${line#*@}
	echo "$time" > "$path"

	unset "$1"

}


check_pre_comp_notes () {

	local nmodtime
	local lmodt_file

	lmodt_file="${1%/*}/ebook/lmodt_$(basename "${1%.*}")"
	nmodtime=$(stat --printf "%Y\n" "$1")
	if [[ -f "$lmodt_file" && "$nmodtime" -le $(cat "$lmodt_file") ]]; then
		return 0
	fi
	modified_time_norg+="$lmodt_file@$nmodtime"$'\n'
	return 1

}

check_pre_comp_syllabus_markdown () {

	local imodtime=""
	local norgfiles=$(find "$1" \( -iname syllabus*.norg -o -iname index.norg \))

	while read -r file
	do
		imodtime+=$(stat --printf "%Y\n" "$file")$'\n'
	done <<<"$norgfiles"

	imodtime=$(sort <<<"$imodtime" | tail -n 1)

	if [[ -f "$1/ebook/lmodt_syllabus" && $imodtime -le $(cat "$1/ebook/lmodt_syllabus") ]]; then
		return 0
	fi
	modified_time_norg+="$1/ebook/lmodt_syllabus@$imodtime"$'\n'
	return 1
}

check_pre_comp_cover () {

	if [[ -f "${1}.png" && -f "${1}_title" ]]; then
		if [[ $2 == $(cat "${1}_title") ]]; then
			return 0
		fi
	fi
	modified_cover_title="${1}_title@$2"
	return 1
}

update_lmodt () {

	# First Arg --> directory that last converted to markdown
	
	local nf_notes

	if ! grep "lmodt_syllabus" <<<"$modified_time_norg" > /dev/null 2>&1 ; then
		check_pre_comp_syllabus_markdown "$1"
	fi

	nf_notes=$(find "$1" -type f -iname notes*.norg)

	while read -r file
	do
		if ! grep "lmodt_$(basename "${file%.*}")" <<<"$modified_time_norg" > /dev/null 2>&1 ; then
			check_pre_comp_notes "$file"
		fi
	done <<<"$nf_notes"

}

update_lmodt "$1"
exit

gen_cover_img () {

	# First Arg --> Path to the norg file with the metadata for title
	# Second Arg --> Subtitle

	local dir=${1%/*}
	local tmpdir="$TMPDIR/epubconv"
	local font="$HOME/.fonts/FiraCode.ttf"
	local title

	mkdir "$tmpdir" > /dev/null 2>&1

	title=$(sed -n "/@document.meta/,/@end/{/^title: /{s/^title: //p}}" "$1")

	if ! check_pre_comp_cover "$dir/ebook/cover_$2" "$title"; then

		convert -background none -fill black -font "$font" -pointsize 65 -size 600x810 -gravity north caption:"$title" "$tmpdir/title.png"
		convert -background none -fill black -font "$font" -pointsize 65 -size 600x810 -gravity south caption:"$2" "$tmpdir/subtitle.png"
		convert -size 800x1080 xc:white "$tmpdir/back.png"
		composite -gravity center "$tmpdir/title.png" "$tmpdir/back.png" "$tmpdir/first.png"
		composite -gravity center "$tmpdir/subtitle.png" "$tmpdir/first.png" "$dir/ebook/cover_$2.png"

		write_new_modt "modified_cover_title"
	fi


}

gen_markdown () {

	# First Arg --> Path to the directory that wants to be converted

	local dir=$(sed "s; ;\\\ ;" <<<"$1")

	nvim -R -c ":Neorg export directory $dir markdown $dir/ebook" -c "q" "$1/../index.norg" > /dev/null 2>&1

	[[ -d "$1/ebook" ]] || exit 1


}

gen_notes_ebook () {
	echo hai
}

notes_ebook () {

	local norg_files

	while read -r dir
	do
		[[ -z $dir ]] && continue
		norg_files=$(find "$dir" -iname notes*.norg)
		while read -r file
		do
			check_metadata "$file"
			if ! check_pre_comp_notes "$file" ; then
				gen_markdown "$dir"
			fi

		done <<<"$norg_files"

	done <<<"$@"
}


gen_syllabus_epub () {

	# First Arg --> Path to the directory that wants to be converted

	local cover_img
	local md_files
	local epub_name

	epub_name=$(sed -n "/@document.meta/,/@end/{/^title: /{s/^title: //p}}" "$1/index.norg" | tr '[:upper:]' '[:lower:]' | tr " " _)

	gen_cover_img "$1/index.norg" "syllabus"
	cover_img="$1/ebook/cover_syllabus.png"

	md_files=$(find "$1/ebook" -iname syllabus*.md | sort)
	sed -n "1,/---/p" "$1/ebook/index.md" > "$1/ebook/ebook.md"

	while read -r file
	do
		sed "1,/---/d" "$file" >> "$1/ebook/ebook.md"
	done <<<"$md_files"

	pandoc --epub-cover-image "$cover_img" -o "$1/${epub_name}_syllabus.epub" "$1/ebook/ebook.md"

}

syllabus_ebook () {

	local title

	while read -r dir
	do

		[[ -z $dir ]] && continue

		check_metadata "$dir/index.norg"

		title=$(sed -n "/@document.meta/,/@end/{/^title: /{s/^title: //p}}" "$dir/index.norg" | tr '[:upper:]' '[:lower:]' | tr " " _)

		if ! check_pre_comp_syllabus_markdown "$dir" ; then
			gen_markdown "$dir"
			gen_syllabus_epub "$dir"
		elif [[ ! -f "$dir/${title}_syllabus.epub" ]]; then
			gen_syllabus_epub "$dir"
		fi
		write_new_modt "modified_time_norg"
	done <<<"$@"
}

for arg in "$@"
do
	case $arg in 
		-s)
			gen_type=syllabus
			;;
		-n)
			gen_type=notes
			;;
		-sn|-ns)
			gen_type=""
			;;
		*)
			[[ -d $arg ]] || continue
			if [[ $gen_type == "syllabus" ]]; then
				dirs_for_syllabus+="${arg}"$'\n'
			elif [[ $gen_type == "notes" ]]; then
				dirs_for_notes+="${arg}"$'\n'
			elif [[ $gen_type == "" ]]; then
				dirs_for_syllabus+="${arg}"$'\n'
				dirs_for_notes+="${arg}"$'\n'
			fi
			;;
	esac
done

#syllabus_ebook "${dirs_for_syllabus}"
notes_ebook "${dirs_for_notes}"
