#!/data/data/com.termux/files/usr/bin/bash

okcmd=""

usage () {
	printf "wip\n"
}

# i have no idea what this thing is trying to do :), maybe checking
# whether shizuku is running... ? right now we are not calling this
# function
check_for_shizuku () {
	if [[ ! $(rish -c "cat /data/local/tmp/checkshizuku") == "yes" ]]; then
		am start moe.shizuku.privileged.api/moe.shizuku.manager.MainActivity > /dev/null 2>&1
		exit 1
	fi
}

get_pkgs () {
    # you would never. ever. want to disable these two.
	rish -c "sh /sdcard/pkgdisabler/scripts/getpkglist.sh" \
        | grep -vi termux \
        | grep -vi shizuku \
        | fzf -m || exit 1
}

ask_confirm () {
	local can
	printf "Do you really want to toggle $1 ? [yes|no]: "
	read -r can
	case $can in
		[Yy][Ee][Ss])
			return
			;;
		*)
			exit 1
			;;
	esac
}

toggle_pkgstate() {
	local pkgname
	local pkgstate

	while IFS='\n' read -r line
	do
		line=${line#*[}
		pkgname=${line%%]*}
		pkgstate=$(tr -d ] <<<"${line##*[}")
		case $pkgname in
			moe.shizuku.privileged.api)
				# ask_confirm $pkgname
                exit 1
				;;
			com.termux)
				printf "lol, you thought...\n"
				exit 1
				;;
			*)
				;;
		esac
		if [[ $pkgstate == "Disabled" ]]; then
            case $pkgname in
                org.polymorphicshade.tubular)
                    echo "Tubular: Ohh please, fuck off."
                    continue
                    ;;
                com.olx.southasia)
                    echo "OLX: Ohh please, fuck off."
                    continue
                    ;;
                *)
                    ;;
            esac
			okcmd+=$(printf "pm enable ${pkgname};")
		elif [[ $pkgstate == "Enabled" ]]; then
			okcmd+=$(printf "pm disable-user ${pkgname};")
		fi
	done <<<"$@"
	# Because calling rish for toggling pkg state will breaks the while loop for
	# some reason
	rish -c "$okcmd"
}

# check_for_shizuku
toggle_pkgstate "$(get_pkgs)"
