#!/bin/bash

Bat_Cap_File="/sys/class/power_supply/BAT0/capacity"

while true
do
    # TODO: this is lame, fix it.

    Bat_Cap=$(cat $Bat_Cap_File)

    for i in $(seq 1 5)
    do
        if [[ $(date +"%p") == "AM" ]]; then
            xsetroot -name "   󰪥   󰪥   󰪥   󰪥      ${Bat_Cap}    $(date +"%I:%M:%S ")    "
        else
            xsetroot -name "   󰪥   󰪥   󰪥   󰪥      ${Bat_Cap}    $(date +"%I:%M:%S ") 󰪥   "
        fi
        sleep 1
    done

done

#  // large
#  // large
#  // large
# 󱤅 // battery saver
# 󰪥 // battery normal
# 󰠠 // battery charging


# 
# 󰫽 󰫺
# 󱎥
# 󰫺
#   󰪥  
#  // large
#  // small
# 󰪥
#  //large
#  // small
#  // um
#  // really small
