#!/bin/bash

unset Meta
unset Artists
unset Title
unset Query
unset File

unset Verbose

Retro_dir="/sdcard/RetroMusic"

mkdir "${Retro_dir}/json" > /dev/null 2>&1
mkdir "${Retro_dir}/lyrics" > /dev/null 2>&1

verbose_log() {

    if [[ $Verbose == 1 ]]; then
        echo "${@}"
    fi

}

# First Arg --> path to the wfile
gen_meta() {

    Meta="$(id3ted -l "${1}")"

    if [[ -z "${Meta}" ]]; then
        verbose_log "No metadata"
        exit 1
    fi

    if [[ -z "${Title}" ]]; then
        Title=$(grep "^TIT2: " <<<"${Meta}" | sed 's/^TIT2: //')
    fi

    if [[ -z "${Artists}" ]]; then
        Artists=$(grep "^TPE1: " <<<"${Meta}" | sed 's/^TPE1: //')
    fi

}

gen_lrc() {

    local q_artists
    local q_title
    local response
    local synced

    if [[ -z "${Query}" ]]; then
        q_title="$(tr " " "+" <<<"$Title" | tr "‘" "'" | tr -d "\"")"
        q_artists="$(tr " " "+" <<<"$Artists" | tr -d "\"")"
        Query="${q_title}+${q_artists}"
    fi

    response="$(curl -s "https://lrclib.net/api/search?q=${Query}")"

    if [[ "$response" =~ "[]" ]]; then
        verbose_log "No response"
        exit 1
    fi

    echo "{\"query\": {\"title\": \"${Title}\", \"artists\": \"${Artists}\", \"queryString\": \"${Query}\", \"file\": \"${File}\"}, \"response\": ${response} }" > "${Retro_dir}/json/${Title} - ${Artists}.json"

    synced="$(jq -r '[(.[] | select(.syncedLyrics != null))][0]["syncedLyrics"]' <<<"${response}")"

    if [[ -z "$synced" ]]; then
        verbose_log "No synced"
        exit 1
    fi

    printf "$synced\n" > "${Retro_dir}/lyrics/${Title} - ${Artists}.lrc"

}

while [ : ]
do
    [[ "${1}" == "" ]] && break
    case "${1}" in
        --title)
            shift 1
            Title="${1}"
            ;;
        --artists)
            shift 1
            Artists="${1}"
            ;;
        --query)
            shift 1
            Query="$(tr " " "+" <<<"${1}" | tr -d "\"")"
            ;;
        --verbose)
            Verbose=1
            ;;
        *)
            File="${1}"
            ;;
    esac

    shift 1
done

File=$(readlink -e "${File}")

if [[ -z "$File" ]]; then
    if [[ -z "$Artists" || -z "$Title" ]]; then
        verbose_log "No File"
        exit 1
    fi
fi

if [[ -z "$Artists" || -z "$Title" ]]; then
    gen_meta "$File"
fi

gen_lrc

exit 0
